/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: call-method.json");
    return;
  }

  const config = {
    "_sourceFile": "call-method.json",
    "object": "CALL_METHOD",
    "match": {
      "startPhrase": "CALL METHOD"
    },
    "extras": {
      "type": "callMethod"
    },
    "keywordLabels": {
      "CALL": "stmt",
      "METHOD": "method",
      "EXPORTING": "exporting",
      "IMPORTING": "importing",
      "CHANGING": "changing",
      "RECEIVING": "receiving",
      "EXCEPTIONS": "exceptions"
    },
    "keywordPhrases": {
      "CALL METHOD": "call-method"
    },
    "captureRules": [
      {
        "after": "CALL METHOD",
        "name": "target",
        "label": "target",
        "capture": "rest",
        "stopTokens": [
          "EXPORTING",
          "IMPORTING",
          "CHANGING",
          "RECEIVING",
          "EXCEPTIONS"
        ]
      },
      {
        "after": "EXPORTING",
        "name": "exportingRaw",
        "label": "exporting",
        "capture": "rest",
        "stopTokens": [
          "IMPORTING",
          "CHANGING",
          "RECEIVING",
          "EXCEPTIONS"
        ]
      },
      {
        "after": "IMPORTING",
        "name": "importingRaw",
        "label": "importing",
        "capture": "rest",
        "stopTokens": [
          "EXPORTING",
          "CHANGING",
          "RECEIVING",
          "EXCEPTIONS"
        ]
      },
      {
        "after": "CHANGING",
        "name": "changingRaw",
        "label": "changing",
        "capture": "rest",
        "stopTokens": [
          "EXPORTING",
          "IMPORTING",
          "RECEIVING",
          "EXCEPTIONS"
        ]
      },
      {
        "after": "RECEIVING",
        "name": "receivingRaw",
        "label": "receiving",
        "capture": "rest",
        "stopTokens": [
          "EXPORTING",
          "IMPORTING",
          "CHANGING",
          "EXCEPTIONS"
        ]
      },
      {
        "after": "EXCEPTIONS",
        "name": "exceptionsRaw",
        "label": "exceptions",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
