/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: catch.json");
    return;
  }

  const config = {
    "_sourceFile": "catch.json",
    "object": "CATCH",
    "match": {
      "startKeyword": "CATCH"
    },
    "keywordLabels": {
      "CATCH": "stmt",
      "INTO": "into"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "CATCH",
        "name": "exception",
        "label": "exception",
        "capture": "rest",
        "stopTokens": [
          "INTO"
        ]
      },
      {
        "after": "INTO",
        "name": "into",
        "label": "into"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
