/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: clear.json");
    return;
  }

  const config = {
    "_sourceFile": "clear.json",
    "object": "CLEAR",
    "match": {
      "startKeyword": "CLEAR"
    },
    "keywordLabels": {
      "CLEAR": "stmt",
      "WITH": "with"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "CLEAR",
        "name": "target",
        "label": "target"
      },
      {
        "after": "WITH",
        "name": "with",
        "label": "with"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
