/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: constants.json");
    return;
  }

  const config = {
    "_sourceFile": "constants.json",
    "object": "CONSTANTS",
    "match": {
      "startKeyword": "CONSTANTS"
    },
    "keywordLabels": {
      "CONSTANTS": "stmt",
      "TYPE": "type",
      "LIKE": "like",
      "REF": "ref",
      "TO": "to",
      "VALUE": "value",
      "LENGTH": "length",
      "DECIMALS": "decimals"
    },
    "keywordPhrases": {
      "REF TO": "ref-to"
    },
    "captureRules": [
      {
        "after": "CONSTANTS",
        "name": "name",
        "label": "const-name",
        "descKey": "name"
      },
      {
        "after": "TYPE REF TO",
        "name": "refTo",
        "label": "ref-to",
        "descKey": "refTo"
      },
      {
        "after": "TYPE",
        "name": "type",
        "label": "type-name",
        "descKey": "type"
      },
      {
        "after": "LIKE",
        "name": "like",
        "label": "like-name",
        "descKey": "like"
      },
      {
        "after": "VALUE",
        "name": "value",
        "label": "value",
        "descKey": "value"
      },
      {
        "after": "LENGTH",
        "name": "length",
        "label": "length"
      },
      {
        "after": "DECIMALS",
        "name": "decimals",
        "label": "decimals"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
