/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: else.json");
    return;
  }

  const config = {
    "_sourceFile": "else.json",
    "object": "ELSE",
    "match": {
      "startKeyword": "ELSE"
    },
    "keywordLabels": {
      "ELSE": "stmt"
    },
    "keywordPhrases": {},
    "captureRules": []
  };
  window.AbapParser.registerConfig(config);
})();
