/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: if.json");
    return;
  }

  const config = {
    "_sourceFile": "if.json",
    "object": "IF",
    "match": {
      "startKeyword": "IF"
    },
    "block": {
      "endKeyword": "ENDIF"
    },
    "keywordLabels": {
      "IF": "stmt",
      "AND": "and",
      "OR": "or",
      "NOT": "not",
      "IS": "is",
      "INITIAL": "initial"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "IF",
        "name": "condition",
        "label": "condition",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
