/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: message.json");
    return;
  }

  const config = {
    "_sourceFile": "message.json",
    "object": "MESSAGE",
    "match": {
      "startKeyword": "MESSAGE"
    },
    "extras": {
      "type": "message"
    },
    "keywordLabels": {
      "MESSAGE": "stmt",
      "ID": "id",
      "TYPE": "message-type",
      "NUMBER": "number",
      "WITH": "with",
      "DISPLAY": "display",
      "LIKE": "like",
      "INTO": "into",
      "RAISING": "raising"
    },
    "keywordPhrases": {
      "DISPLAY LIKE": "display-like"
    },
    "captureRules": [
      {
        "after": "MESSAGE",
        "name": "message",
        "label": "message"
      },
      {
        "after": "ID",
        "name": "id",
        "label": "id"
      },
      {
        "after": "TYPE",
        "name": "messageType",
        "label": "message-type"
      },
      {
        "after": "NUMBER",
        "name": "number",
        "label": "number"
      },
      {
        "after": "WITH",
        "name": "withRaw",
        "label": "with",
        "capture": "rest",
        "stopTokens": [
          "DISPLAY",
          "INTO",
          "RAISING"
        ]
      },
      {
        "after": "DISPLAY LIKE",
        "name": "displayLike",
        "label": "display-like"
      },
      {
        "after": "INTO",
        "name": "into",
        "label": "into"
      },
      {
        "after": "RAISING",
        "name": "raising",
        "label": "raising"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
