/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: method.json");
    return;
  }

  const config = {
    "_sourceFile": "method.json",
    "object": "METHOD",
    "match": {
      "startKeyword": "METHOD"
    },
    "block": {
      "endKeyword": "ENDMETHOD"
    },
    "keywordLabels": {
      "METHOD": "stmt"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "METHOD",
        "name": "name",
        "label": "method-name",
        "descKey": "name"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
