/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: ranges.json");
    return;
  }

  const config = {
    "_sourceFile": "ranges.json",
    "object": "RANGES",
    "match": {
      "startKeyword": "RANGES"
    },
    "keywordLabels": {
      "RANGES": "stmt",
      "FOR": "for",
      "TYPE": "type",
      "LIKE": "like",
      "REF": "ref",
      "TO": "to"
    },
    "keywordPhrases": {
      "REF TO": "ref-to"
    },
    "captureRules": [
      {
        "after": "RANGES",
        "name": "name",
        "label": "range-name",
        "descKey": "name"
      },
      {
        "after": "FOR",
        "name": "for",
        "label": "for",
        "descKey": "for"
      },
      {
        "after": "TYPE REF TO",
        "name": "refTo",
        "label": "ref-to",
        "descKey": "refTo"
      },
      {
        "after": "TYPE",
        "name": "type",
        "label": "type",
        "descKey": "type"
      },
      {
        "after": "LIKE",
        "name": "like",
        "label": "like",
        "descKey": "like"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
