/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: types.json");
    return;
  }

  const config = {
    "_sourceFile": "types.json",
    "object": "TYPES",
    "match": {
      "startKeyword": "TYPES"
    },
    "keywordLabels": {
      "TYPES": "stmt",
      "TYPE": "type",
      "LIKE": "like",
      "BEGIN": "begin",
      "OF": "of",
      "END": "end"
    },
    "keywordPhrases": {
      "BEGIN OF": "begin-of",
      "END OF": "end-of"
    },
    "captureRules": [
      {
        "after": "TYPES BEGIN OF",
        "name": "name",
        "label": "type-name"
      },
      {
        "after": "TYPES END OF",
        "name": "name",
        "label": "type-name"
      },
      {
        "after": "TYPES",
        "name": "name",
        "label": "type-name"
      },
      {
        "after": "TYPE",
        "name": "type",
        "label": "type"
      },
      {
        "after": "LIKE",
        "name": "like",
        "label": "like"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
