/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: write.json");
    return;
  }

  const config = {
    "_sourceFile": "write.json",
    "object": "WRITE",
    "match": {
      "startKeyword": "WRITE"
    },
    "extras": {
      "type": "write"
    },
    "keywordLabels": {
      "WRITE": "stmt",
      "AT": "at",
      "TO": "to",
      "NO-GAP": "no-gap",
      "LEFT-JUSTIFIED": "left-justified",
      "RIGHT-JUSTIFIED": "right-justified",
      "CENTERED": "centered",
      "UNDER": "under",
      "NO-ZERO": "no-zero",
      "NO-SIGN": "no-sign",
      "NO-GROUPING": "no-grouping",
      "CURRENCY": "currency",
      "DECIMALS": "decimals",
      "EXPONENT": "exponent",
      "ROUND": "round",
      "UNIT": "unit",
      "USING": "using",
      "EDIT": "edit",
      "MASK": "mask"
    },
    "keywordPhrases": {
      "USING EDIT MASK": "using-edit-mask"
    },
    "captureRules": [
      {
        "after": "WRITE",
        "name": "output",
        "label": "output"
      },
      {
        "after": "AT",
        "name": "position",
        "label": "position"
      },
      {
        "after": "TO",
        "name": "destination",
        "label": "to"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
