/* AUTO-GENERATED by scripts/build-runtime-bundles.js. Do not edit this file directly. */
// bundled from: viewer/app/core/01-runtime-state.js
"use strict";

window.AbapViewerModules = window.AbapViewerModules || {};
window.AbapViewerModules.parts = window.AbapViewerModules.parts || {};
window.AbapViewerRuntime = window.AbapViewerRuntime || {};
window.AbapViewerRuntime.api = window.AbapViewerRuntime.api || {};

  const els = {
    parseBtn: document.getElementById("parseBtn"),
    themeToggle: document.getElementById("themeToggle"),
    descBtn: document.getElementById("descBtn"),
    settingsBtn: document.getElementById("settingsBtn"),
    inputText: document.getElementById("inputText"),
    inputGutter: document.getElementById("inputGutter"),
    inputGutterContent: document.getElementById("inputGutterContent"),
    mainLayout: document.getElementById("mainLayout"),
    panelSplitter: document.getElementById("panelSplitter"),
    buildInfo: document.getElementById("buildInfo"),
    rightPanelTitle: document.getElementById("rightPanelTitle"),
    rightTabTemplateBtn: document.getElementById("rightTabTemplateBtn"),
    rightTabDescBtn: document.getElementById("rightTabDescBtn"),
    templatePreviewPanel: document.getElementById("templatePreviewPanel"),
    templateKeyMode: document.getElementById("templateKeyMode"),
    templateCopyTableOnly: document.getElementById("templateCopyTableOnly"),
    templateCopySelectedBtn: document.getElementById("templateCopySelectedBtn"),
    templateCopyAllBtn: document.getElementById("templateCopyAllBtn"),
    templateResetBtn: document.getElementById("templateResetBtn"),
    templateExportBtn: document.getElementById("templateExportBtn"),
    templateImportBtn: document.getElementById("templateImportBtn"),
    templateApplyBtn: document.getElementById("templateApplyBtn"),
    templateImportInput: document.getElementById("templateImportInput"),
    templateConfigError: document.getElementById("templateConfigError"),
    templateConfigJson: document.getElementById("templateConfigJson"),
    templatePreviewOutput: document.getElementById("templatePreviewOutput"),
    declDescJsonBtn: document.getElementById("declDescJsonBtn"),
    declDescPanel: document.getElementById("declDescPanel"),
    error: document.getElementById("error"),
    jsonModal: document.getElementById("jsonModal"),
    jsonTitle: document.getElementById("jsonTitle"),
    jsonPre: document.getElementById("jsonPre"),
    jsonCopyBtn: document.getElementById("jsonCopyBtn"),
    jsonCloseBtn: document.getElementById("jsonCloseBtn"),
    declDescSearch: document.getElementById("declDescSearch"),
    declDescMissingOnly: document.getElementById("declDescMissingOnly"),
    declDescTypes: document.getElementById("declDescTypes"),
    declDescSummary: document.getElementById("declDescSummary"),
    declDescTable: document.getElementById("declDescTable"),
    editModal: document.getElementById("editModal"),
    editLabel: document.getElementById("editLabel"),
    editHint: document.getElementById("editHint"),
    editSingleWrap: document.getElementById("editSingleWrap"),
    editDesc: document.getElementById("editDesc"),
    editStructWrap: document.getElementById("editStructWrap"),
    editStructDesc: document.getElementById("editStructDesc"),
    editItemDesc: document.getElementById("editItemDesc"),
    editSkipNormalize: document.getElementById("editSkipNormalize"),
    editSaveBtn: document.getElementById("editSaveBtn"),
    editClearBtn: document.getElementById("editClearBtn"),
    editCancelBtn: document.getElementById("editCancelBtn"),
    settingsModal: document.getElementById("settingsModal"),
    settingsNormalizeDesc: document.getElementById("settingsNormalizeDesc"),
    settingsDeclTypes: document.getElementById("settingsDeclTypes"),
    settingsStructTemplate: document.getElementById("settingsStructTemplate"),
    settingsNameTemplates: document.getElementById("settingsNameTemplates"),
    settingsSaveBtn: document.getElementById("settingsSaveBtn"),
    settingsResetBtn: document.getElementById("settingsResetBtn"),
    settingsCloseBtn: document.getElementById("settingsCloseBtn"),
    appHeader: document.getElementById("appHeader"),
    appControls: document.getElementById("appControls"),
    appContainer: document.querySelector(".container")
  };

  const state = {
    data: null,
    renderObjects: [],
    performSourceRegistry: null,
    inputMode: "abap",
    inputLineCount: 0,
    inputGutterButtonsByLine: new Map(),
    inputGutterTargetsByLine: new Map(),
    theme: "dark",
    rightTab: "template",
    templateConfig: null,
    templateConfigDraft: "",
    templatePreviewCache: null,
    selectedTemplateIndex: "",
    selectedTemplateIndexes: new Set(),
    templateSelectionAnchorIndex: "",
    selectedDeclKey: "",
    descOverrides: {},
    descOverridesLegacy: {},
    constantInitializers: new Map(),
    activeEdit: null,
    inputLineOffsets: [],
    settings: null,
    layoutLeftPane: 48,
    templateVirtual: {
      items: [],
      itemCount: 0,
      start: 0,
      end: 0,
      lastScrollTop: 0,
      scrollDir: "down",
      pendingRaf: 0,
      isAdjustingScroll: false,
      avgItemHeight: 140,
      unknownItemHeight: 140,
      estimateCalibrated: false,
      adjustmentRaf: 0,
      adjustmentGeneration: 0,
      needsScrollSync: false,
      isRenderTransaction: false,
      geometryEpoch: 0,
      lineTargetMap: new Map(),
      isInitialized: false
    },
    inputGutterVirtual: {
      lineCount: 0,
      startLine: 1,
      endLine: 1,
      lineHeightPx: 18,
      topPadPx: 0,
      bottomPadPx: 0,
      pendingRaf: 0,
      lastScrollTop: 0,
      overscanLines: 6,
      isInitialized: false
    }
  };

  const DESC_STORAGE_KEY_V2 = "abap-parser-viewer.declDescOverrides.v2";
  const DESC_STORAGE_KEY_LEGACY_V1 = "abap-parser-viewer.descOverrides.v1";
  const SETTINGS_STORAGE_KEY_V1 = "abap-parser-viewer.settings.v1";
  const TEMPLATE_CONFIG_STORAGE_KEY_V1 = "abap-parser-viewer.templateConfig.v1";
  const THEME_STORAGE_KEY_V1 = "abap-parser-viewer.theme.v1";
  const LAYOUT_SPLIT_STORAGE_KEY_V1 = "abap-parser-viewer.layoutSplit.v1";
  const LAYOUT_SPLIT_DEFAULT = 48;
  const LAYOUT_SPLIT_MIN = 28;
  const LAYOUT_SPLIT_MAX = 72;
  const MOBILE_LAYOUT_QUERY = "(max-width: 980px)";
  const RENDER_TREE_OPTIONS = Object.freeze({
    expandPerformForms: true,
    hideFormRoots: true,
    maxExpandDepth: Number.POSITIVE_INFINITY
  });

  const DECL_TYPE_OPTIONS = [
    "DATA",
    "INLINE",
    "TYPES",
    "PARAMETERS",
    "SELECT-OPTIONS",
    "CONSTANTS",
    "RANGES",
    "STATICS",
    "CLASS-DATA",
    "FIELD-SYMBOLS",
    "FORM_PARAM",
    "METHOD_PARAM"
  ];

  const NAME_CODE_OPTIONS = [
    { code: "CN", label: "HẰNG" },
    { code: "DS", label: "STRUCT" },
    { code: "DT", label: "TABLE" },
    { code: "DR", label: "RANGETABLE" },
    { code: "DF", label: "BIẾN" },
    { code: "FL", label: "CỜ" },
    { code: "FS", label: "FIELDSYMBOL" }
  ];

  const DEFAULT_SETTINGS = {
    normalizeDeclDesc: true,
    declFilterTypes: [
      "DATA",
      "INLINE",
      "TYPES",
      "PARAMETERS",
      "SELECT-OPTIONS",
      "CONSTANTS",
      "RANGES",
      "STATICS",
      "CLASS-DATA",
      "FIELD-SYMBOLS",
      "FORM_PARAM",
      "METHOD_PARAM"
    ],
    structDescTemplate: "{{struct}}-{{item}}",
    nameTemplatesByCode: {
      CN: "HẰNG:{{desc}}",
      DS: "STRUCT:{{desc}}",
      DT: "TABLE:{{desc}}",
      DR: "RANGETABLE:{{desc}}",
      DF: "BIẾN:{{desc}}",
      FL: "CỜ:{{desc}}",
      FS: "FIELDSYMBOL:{{desc}}"
    }
  };

  const SAMPLE_ABAP = [
    "REPORT zflight_operations_overview.",
    "",
    "*---------------------------------------------------------------------*",
    "* Flight operations overview",
    "* The report validates a planning request, loads demo flight data,",
    "* calculates availability, builds an operational priority list, and",
    "* prints a concise report together with an audit trail.",
    "*---------------------------------------------------------------------*",
    "",
    "TABLES:",
    "  sflight,",
    "  spfli,",
    "  scarr.",
    "CONSTANTS:",
    "  gc_status_open    TYPE char12 VALUE 'OPEN',",
    "  gc_status_limited TYPE char12 VALUE 'LIMITED',",
    "  gc_status_full    TYPE char12 VALUE 'FULL',",
    "  gc_status_closed  TYPE char12 VALUE 'CLOSED',",
    "  gc_priority_high  TYPE char1  VALUE '1',",
    "  gc_priority_mid   TYPE char1  VALUE '2',",
    "  gc_priority_low   TYPE char1  VALUE '3'.",
    "TYPES:",
    "  BEGIN OF ty_request,",
    "    carrid       TYPE sflight-carrid,",
    "    connid       TYPE sflight-connid,",
    "    date_low     TYPE sflight-fldate,",
    "    date_high    TYPE sflight-fldate,",
    "    min_free     TYPE i,",
    "    include_full TYPE abap_bool,",
    "  END OF ty_request.",
    "TYPES:",
    "  BEGIN OF ty_flight,",
    "    carrid             TYPE sflight-carrid,",
    "    connid             TYPE sflight-connid,",
    "    fldate             TYPE sflight-fldate,",
    "    price              TYPE sflight-price,",
    "    currency           TYPE sflight-currency,",
    "    planetype          TYPE sflight-planetype,",
    "    seatsmax           TYPE sflight-seatsmax,",
    "    seatsocc           TYPE sflight-seatsocc,",
    "    seatsfree          TYPE i,",
    "    occupancy_percent  TYPE p LENGTH 5 DECIMALS 1,",
    "    cityfrom           TYPE spfli-cityfrom,",
    "    cityto             TYPE spfli-cityto,",
    "    airpfrom           TYPE spfli-airpfrom,",
    "    airpto             TYPE spfli-airpto,",
    "    carrname           TYPE scarr-carrname,",
    "    route_text         TYPE string,",
    "    status             TYPE char12,",
    "    priority           TYPE char1,",
    "  END OF ty_flight.",
    "TYPES ty_t_flight TYPE STANDARD TABLE OF ty_flight",
    "  WITH NON-UNIQUE SORTED KEY priority_key COMPONENTS priority.",
    "TYPES:",
    "  BEGIN OF ty_route,",
    "    carrid   TYPE spfli-carrid,",
    "    connid   TYPE spfli-connid,",
    "    cityfrom TYPE spfli-cityfrom,",
    "    cityto   TYPE spfli-cityto,",
    "    airpfrom TYPE spfli-airpfrom,",
    "    airpto   TYPE spfli-airpto,",
    "  END OF ty_route.",
    "TYPES ty_t_route TYPE SORTED TABLE OF ty_route",
    "  WITH UNIQUE KEY carrid connid.",
    "TYPES:",
    "  BEGIN OF ty_carrier,",
    "    carrid   TYPE scarr-carrid,",
    "    carrname TYPE scarr-carrname,",
    "  END OF ty_carrier.",
    "TYPES ty_t_carrier TYPE SORTED TABLE OF ty_carrier",
    "  WITH UNIQUE KEY carrid.",
    "TYPES:",
    "  BEGIN OF ty_summary,",
    "    carrid       TYPE sflight-carrid,",
    "    flight_count TYPE i,",
    "    seatsmax     TYPE i,",
    "    seatsocc     TYPE i,",
    "    seatsfree    TYPE i,",
    "  END OF ty_summary.",
    "TYPES ty_t_summary TYPE HASHED TABLE OF ty_summary",
    "  WITH UNIQUE KEY carrid.",
    "TYPES:",
    "  BEGIN OF ty_audit,",
    "    sequence TYPE i,",
    "    category TYPE char12,",
    "    message  TYPE string,",
    "  END OF ty_audit.",
    "TYPES ty_t_audit TYPE STANDARD TABLE OF ty_audit",
    "  WITH DEFAULT KEY.",
    "",
    "SELECT-OPTIONS:",
    "  s_carr FOR sflight-carrid DEFAULT 'LH',",
    "  s_conn FOR sflight-connid,",
    "  s_date FOR sflight-fldate.",
    "",
    "PARAMETERS:",
    "  p_minfr TYPE i DEFAULT 5,",
    "  p_full  AS CHECKBOX DEFAULT abap_false.",
    "",
    "DATA:",
    "  gs_request         TYPE ty_request,",
    "  gs_preview_request TYPE ty_request,",
    "  gt_flight_source   TYPE STANDARD TABLE OF sflight,",
    "  gt_routes          TYPE ty_t_route,",
    "  gt_carriers        TYPE ty_t_carrier,",
    "  gt_report          TYPE ty_t_flight,",
    "  gt_priority        TYPE ty_t_flight,",
    "  gt_summary         TYPE ty_t_summary,",
    "  gt_audit           TYPE ty_t_audit.",
    "",
    "DATA:",
    "  gv_request_valid   TYPE abap_bool,",
    "  gv_preview_valid   TYPE abap_bool,",
    "  gv_message         TYPE string,",
    "  gv_preview_message TYPE string,",
    "  gv_title           TYPE string,",
    "  gv_priority_copy_to TYPE i,",
    "  gv_weekday         TYPE scal-indicator,",
    "  gv_audit_sequence  TYPE i.",
    "",
    "FIELD-SYMBOLS:",
    "  <ls_audit> TYPE ty_audit,",
    "  <ls_report> TYPE ty_flight.",
    "",
    "CLASS lcl_report_helper DEFINITION FINAL.",
    "  PUBLIC SECTION.",
    "    CLASS-METHODS format_route",
    "      IMPORTING",
    "        iv_cityfrom TYPE spfli-cityfrom",
    "        iv_cityto   TYPE spfli-cityto",
    "      RETURNING",
    "        VALUE(rv_route) TYPE string.",
    "",
    "    CLASS-METHODS write_header",
    "      IMPORTING",
    "        iv_title TYPE string.",
    "ENDCLASS.",
    "",
    "CLASS lcl_report_helper IMPLEMENTATION.",
    "  METHOD format_route.",
    "    rv_route = |{ iv_cityfrom } -> { iv_cityto }|.",
    "  ENDMETHOD.",
    "",
    "  METHOD write_header.",
    "    WRITE: / sy-uline.",
    "    WRITE: / iv_title.",
    "    WRITE: / sy-uline.",
    "  ENDMETHOD.",
    "ENDCLASS.",
    "",
    "INITIALIZATION.",
    "  gv_title = 'Flight Operations Overview'.",
    "  IF s_date[] IS INITIAL.",
    "    s_date-sign = 'I'.",
    "    s_date-option = 'BT'.",
    "    s_date-low = sy-datum.",
    "    s_date-high = sy-datum + 30.",
    "    APPEND s_date.",
    "  ENDIF.",
    "",
    "START-OF-SELECTION.",
    "  PERFORM frm_initialize_run.",
    "  PERFORM frm_build_request.",
    "",
    "  \"First validation represents the submitted selection-screen request.",
    "  PERFORM frm_validate_request",
    "    USING gs_request",
    "    CHANGING gv_request_valid gv_message.",
    "",
    "  IF gv_request_valid = abap_false.",
    "    MESSAGE gv_message TYPE 'S' DISPLAY LIKE 'E'.",
    "    RETURN.",
    "  ENDIF.",
    "",
    "  \"A preview request relaxes the seat threshold for planning context.",
    "  gs_preview_request = gs_request.",
    "  gs_preview_request-min_free = 0.",
    "  PERFORM frm_validate_request",
    "    USING gs_preview_request",
    "    CHANGING gv_preview_valid gv_preview_message.",
    "",
    "  IF gv_preview_valid = abap_false.",
    "    PERFORM frm_add_audit",
    "      USING 'VALIDATION' gv_preview_message.",
    "  ENDIF.",
    "",
    "  \"The original request is checked again immediately before database access.",
    "  PERFORM frm_validate_request",
    "    USING gs_request",
    "    CHANGING gv_request_valid gv_message.",
    "",
    "  IF gv_request_valid = abap_true.",
    "    PERFORM frm_load_reference_data.",
    "    PERFORM frm_build_operational_report.",
    "    PERFORM frm_prepare_priority_list.",
    "    PERFORM frm_merge_priority_window.",
    "    PERFORM frm_apply_report_policy.",
    "    PERFORM frm_build_summary.",
    "    PERFORM frm_write_report.",
    "  ELSE.",
    "    MESSAGE gv_message TYPE 'S' DISPLAY LIKE 'E'.",
    "  ENDIF.",
    "",
    "END-OF-SELECTION.",
    "  PERFORM frm_write_audit_log.",
    "",
    "*---------------------------------------------------------------------*",
    "* Initialize transient state for one report execution.",
    "*---------------------------------------------------------------------*",
    "FORM frm_initialize_run.",
    "  CLEAR:",
    "    gs_request,",
    "    gs_preview_request,",
    "    gv_request_valid,",
    "    gv_preview_valid,",
    "    gv_message,",
    "    gv_preview_message,",
    "    gv_priority_copy_to,",
    "    gv_weekday,",
    "    gv_audit_sequence.",
    "",
    "  REFRESH:",
    "    gt_flight_source,",
    "    gt_routes,",
    "    gt_carriers,",
    "    gt_report,",
    "    gt_priority,",
    "    gt_summary,",
    "    gt_audit.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'START' 'Report execution initialized'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Convert selection-screen values into a stable request structure.",
    "*---------------------------------------------------------------------*",
    "FORM frm_build_request.",
    "  READ TABLE s_carr INDEX 1.",
    "  IF sy-subrc = 0 AND s_carr-option = 'EQ'.",
    "    gs_request-carrid = s_carr-low.",
    "  ENDIF.",
    "",
    "  READ TABLE s_conn INDEX 1.",
    "  IF sy-subrc = 0 AND s_conn-option = 'EQ'.",
    "    gs_request-connid = s_conn-low.",
    "  ENDIF.",
    "",
    "  READ TABLE s_date INDEX 1.",
    "  IF sy-subrc = 0.",
    "    gs_request-date_low = s_date-low.",
    "    IF s_date-high IS INITIAL.",
    "      gs_request-date_high = s_date-low.",
    "    ELSE.",
    "      gs_request-date_high = s_date-high.",
    "    ENDIF.",
    "  ENDIF.",
    "",
    "  gs_request-min_free = p_minfr.",
    "  gs_request-include_full = p_full.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'REQUEST' 'Selection-screen request prepared'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Validate one request without changing any other source chain.",
    "*---------------------------------------------------------------------*",
    "FORM frm_validate_request",
    "  USING",
    "    is_request TYPE ty_request",
    "  CHANGING",
    "    cv_valid   TYPE abap_bool",
    "    cv_message TYPE string.",
    "",
    "  cv_valid = abap_true.",
    "  CLEAR cv_message.",
    "",
    "  IF is_request-date_low IS INITIAL.",
    "    cv_valid = abap_false.",
    "    cv_message = 'Enter a flight date range'.",
    "  ELSEIF is_request-date_high < is_request-date_low.",
    "    cv_valid = abap_false.",
    "    cv_message = 'The high date must not precede the low date'.",
    "  ELSEIF is_request-min_free < 0.",
    "    cv_valid = abap_false.",
    "    cv_message = 'Minimum free seats cannot be negative'.",
    "  ENDIF.",
    "",
    "  IF cv_valid = abap_true.",
    "    cv_message = 'Request is valid'.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Load flights and their route/carrier master data.",
    "*---------------------------------------------------------------------*",
    "FORM frm_load_reference_data.",
    "  SELECT carrid",
    "         connid",
    "         fldate",
    "         price",
    "         currency",
    "         planetype",
    "         seatsmax",
    "         seatsocc",
    "    FROM sflight",
    "    INTO CORRESPONDING FIELDS OF TABLE gt_flight_source",
    "    WHERE carrid IN s_carr",
    "      AND connid IN s_conn",
    "      AND fldate IN s_date.",
    "",
    "  IF gt_flight_source IS INITIAL.",
    "    gv_message = 'No flights match the current request'.",
    "    MESSAGE gv_message TYPE 'S'.",
    "    PERFORM frm_add_audit",
    "      USING 'LOAD' gv_message.",
    "    RETURN.",
    "  ENDIF.",
    "",
    "  SELECT carrid",
    "         connid",
    "         cityfrom",
    "         cityto",
    "         airpfrom",
    "         airpto",
    "    FROM spfli",
    "    INTO TABLE gt_routes",
    "    FOR ALL ENTRIES IN gt_flight_source",
    "    WHERE carrid = gt_flight_source-carrid",
    "      AND connid = gt_flight_source-connid.",
    "",
    "  SELECT carrid",
    "         carrname",
    "    FROM scarr",
    "    INTO TABLE gt_carriers",
    "    FOR ALL ENTRIES IN gt_flight_source",
    "    WHERE carrid = gt_flight_source-carrid.",
    "",
    "  SORT gt_flight_source BY carrid connid fldate.",
    "  SORT gt_routes BY carrid connid.",
    "  SORT gt_carriers BY carrid.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'LOAD' 'Flight, route, and carrier data loaded'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Transform database rows into operational report rows.",
    "*---------------------------------------------------------------------*",
    "FORM frm_build_operational_report.",
    "  DATA:",
    "    ls_source  TYPE sflight,",
    "    ls_route   TYPE ty_route,",
    "    ls_carrier TYPE ty_carrier,",
    "    ls_flight  TYPE ty_flight.",
    "",
    "  LOOP AT gt_flight_source INTO ls_source.",
    "    CLEAR:",
    "      ls_route,",
    "      ls_carrier,",
    "      ls_flight.",
    "",
    "    MOVE-CORRESPONDING ls_source TO ls_flight.",
    "",
    "    READ TABLE gt_routes",
    "      INTO ls_route",
    "      WITH TABLE KEY carrid = ls_source-carrid",
    "                     connid = ls_source-connid.",
    "",
    "    READ TABLE gt_carriers",
    "      INTO ls_carrier",
    "      WITH TABLE KEY carrid = ls_source-carrid.",
    "",
    "    PERFORM frm_enrich_flight",
    "      USING ls_route ls_carrier",
    "      CHANGING ls_flight.",
    "",
    "    APPEND ls_flight TO gt_report.",
    "  ENDLOOP.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'TRANSFORM' 'Operational report rows created'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Add route, availability, status, and priority to one flight.",
    "*---------------------------------------------------------------------*",
    "FORM frm_enrich_flight",
    "  USING",
    "    is_route   TYPE ty_route",
    "    is_carrier TYPE ty_carrier",
    "  CHANGING",
    "    cs_flight  TYPE ty_flight.",
    "",
    "  cs_flight-cityfrom = is_route-cityfrom.",
    "  cs_flight-cityto = is_route-cityto.",
    "  cs_flight-airpfrom = is_route-airpfrom.",
    "  cs_flight-airpto = is_route-airpto.",
    "  cs_flight-carrname = is_carrier-carrname.",
    "",
    "  TRY.",
    "      cs_flight-route_text = lcl_report_helper=>format_route(",
    "        iv_cityfrom = cs_flight-cityfrom",
    "        iv_cityto   = cs_flight-cityto ).",
    "    CATCH cx_root INTO DATA(lx_route).",
    "      cs_flight-route_text = lx_route->get_text( ).",
    "  ENDTRY.",
    "",
    "  PERFORM frm_calculate_availability",
    "    USING cs_flight-seatsmax cs_flight-seatsocc",
    "    CHANGING cs_flight-seatsfree cs_flight-occupancy_percent.",
    "",
    "  PERFORM frm_determine_status",
    "    USING cs_flight-seatsfree cs_flight-fldate",
    "    CHANGING cs_flight-status.",
    "",
    "  PERFORM frm_determine_priority",
    "    USING cs_flight-status cs_flight-seatsfree",
    "    CHANGING cs_flight-priority.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Calculate free seats and occupancy percentage.",
    "*---------------------------------------------------------------------*",
    "FORM frm_calculate_availability",
    "  USING",
    "    iv_seatsmax TYPE sflight-seatsmax",
    "    iv_seatsocc TYPE sflight-seatsocc",
    "  CHANGING",
    "    cv_seatsfree TYPE i",
    "    cv_occupancy TYPE p.",
    "",
    "  cv_seatsfree = iv_seatsmax - iv_seatsocc.",
    "  IF cv_seatsfree < 0.",
    "    cv_seatsfree = 0.",
    "  ENDIF.",
    "",
    "  IF iv_seatsmax > 0.",
    "    cv_occupancy = iv_seatsocc * 100 / iv_seatsmax.",
    "  ELSE.",
    "    CLEAR cv_occupancy.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Derive the operational status from availability and departure date.",
    "*---------------------------------------------------------------------*",
    "FORM frm_determine_status",
    "  USING",
    "    iv_seatsfree TYPE i",
    "    iv_fldate    TYPE sflight-fldate",
    "  CHANGING",
    "    cv_status    TYPE char12.",
    "",
    "  IF iv_fldate < sy-datum.",
    "    cv_status = gc_status_closed.",
    "  ELSEIF iv_seatsfree = 0.",
    "    cv_status = gc_status_full.",
    "  ELSEIF iv_seatsfree <= gs_request-min_free.",
    "    cv_status = gc_status_limited.",
    "  ELSE.",
    "    cv_status = gc_status_open.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Rank rows so operations can review constrained flights first.",
    "*---------------------------------------------------------------------*",
    "FORM frm_determine_priority",
    "  USING",
    "    iv_status    TYPE char12",
    "    iv_seatsfree TYPE i",
    "  CHANGING",
    "    cv_priority  TYPE char1.",
    "",
    "  CASE iv_status.",
    "    WHEN gc_status_limited.",
    "      cv_priority = gc_priority_high.",
    "    WHEN gc_status_full.",
    "      cv_priority = gc_priority_high.",
    "    WHEN gc_status_open.",
    "      IF iv_seatsfree <= gs_request-min_free * 2.",
    "        cv_priority = gc_priority_mid.",
    "      ELSE.",
    "        cv_priority = gc_priority_low.",
    "      ENDIF.",
    "    WHEN OTHERS.",
    "      cv_priority = gc_priority_low.",
    "  ENDCASE.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Build a separate priority queue and create an audit row in place.",
    "*---------------------------------------------------------------------*",
    "FORM frm_prepare_priority_list.",
    "  DATA ls_flight TYPE ty_flight.",
    "",
    "  LOOP AT gt_report INTO ls_flight",
    "    WHERE priority = gc_priority_high",
    "       OR priority = gc_priority_mid.",
    "    APPEND ls_flight TO gt_priority.",
    "  ENDLOOP.",
    "",
    "  SORT gt_priority BY priority seatsfree carrid connid fldate.",
    "",
    "  APPEND INITIAL LINE TO gt_audit ASSIGNING <ls_audit>.",
    "  IF <ls_audit> IS ASSIGNED.",
    "    gv_audit_sequence = gv_audit_sequence + 1.",
    "    <ls_audit>-sequence = gv_audit_sequence.",
    "    <ls_audit>-category = 'PRIORITY'.",
    "    <ls_audit>-message = |Priority queue contains { lines( gt_priority ) } flights|.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Merge a review window with full APPEND LINES OF range additions.",
    "*---------------------------------------------------------------------*",
    "FORM frm_merge_priority_window.",
    "  DESCRIBE TABLE gt_priority LINES gv_priority_copy_to.",
    "",
    "  IF gv_priority_copy_to > 5.",
    "    gv_priority_copy_to = 5.",
    "  ENDIF.",
    "",
    "  IF gv_priority_copy_to > 0.",
    "    APPEND LINES OF gt_priority",
    "      FROM 1",
    "      TO gv_priority_copy_to",
    "      STEP 1",
    "      USING KEY priority_key",
    "      TO gt_report.",
    "",
    "    PERFORM frm_add_audit",
    "      USING 'PRIORITY' 'Priority review window appended to report'.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Apply final display policy and demonstrate targeted table updates.",
    "*---------------------------------------------------------------------*",
    "FORM frm_apply_report_policy.",
    "  DATA ls_flight TYPE ty_flight.",
    "",
    "  IF gs_request-include_full = abap_false.",
    "    DELETE gt_report WHERE status = gc_status_full.",
    "  ENDIF.",
    "",
    "  SORT gt_report BY priority carrid connid fldate.",
    "  DELETE ADJACENT DUPLICATES FROM gt_report",
    "    COMPARING carrid connid fldate.",
    "",
    "  READ TABLE gt_report INTO ls_flight INDEX 1.",
    "  IF sy-subrc = 0.",
    "    ls_flight-route_text = |{ ls_flight-route_text } (lead)|.",
    "    MODIFY gt_report FROM ls_flight INDEX 1.",
    "  ENDIF.",
    "",
    "  LOOP AT gt_report ASSIGNING <ls_report>.",
    "    IF <ls_report>-carrname IS INITIAL.",
    "      <ls_report>-carrname = <ls_report>-carrid.",
    "    ENDIF.",
    "  ENDLOOP.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'POLICY' 'Final report policy applied'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Aggregate capacity by carrier for the report footer.",
    "*---------------------------------------------------------------------*",
    "FORM frm_build_summary.",
    "  DATA:",
    "    ls_flight  TYPE ty_flight,",
    "    ls_summary TYPE ty_summary.",
    "",
    "  LOOP AT gt_report INTO ls_flight.",
    "    CLEAR ls_summary.",
    "    ls_summary-carrid = ls_flight-carrid.",
    "    ls_summary-flight_count = 1.",
    "    ls_summary-seatsmax = ls_flight-seatsmax.",
    "    ls_summary-seatsocc = ls_flight-seatsocc.",
    "    ls_summary-seatsfree = ls_flight-seatsfree.",
    "    COLLECT ls_summary INTO gt_summary.",
    "  ENDLOOP.",
    "",
    "  PERFORM frm_add_audit",
    "    USING 'SUMMARY' 'Carrier totals calculated'.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Print operational rows and carrier totals.",
    "*---------------------------------------------------------------------*",
    "FORM frm_write_report.",
    "  DATA:",
    "    ls_flight  TYPE ty_flight,",
    "    ls_summary TYPE ty_summary,",
    "    lv_date_text TYPE char10.",
    "",
    "  CALL METHOD lcl_report_helper=>write_header",
    "    EXPORTING",
    "      iv_title = gv_title.",
    "",
    "  WRITE: / 'Carrier',",
    "           12 'Connection',",
    "           25 'Date',",
    "           37 'Route',",
    "           70 'Free',",
    "           78 'Load %',",
    "           88 'Status'.",
    "  WRITE: / sy-uline.",
    "",
    "  LOOP AT gt_report INTO ls_flight.",
    "    WRITE ls_flight-fldate TO lv_date_text.",
    "    WRITE: / ls_flight-carrid,",
    "             12 ls_flight-connid,",
    "             25 lv_date_text,",
    "             37 ls_flight-route_text,",
    "             70 ls_flight-seatsfree,",
    "             78 ls_flight-occupancy_percent,",
    "             88 ls_flight-status.",
    "  ENDLOOP.",
    "",
    "  SKIP 2.",
    "  WRITE: / 'Carrier totals'.",
    "  WRITE: / sy-uline.",
    "",
    "  LOOP AT gt_summary INTO ls_summary.",
    "    WRITE: / ls_summary-carrid,",
    "             12 ls_summary-flight_count,",
    "             25 ls_summary-seatsmax,",
    "             38 ls_summary-seatsocc,",
    "             51 ls_summary-seatsfree.",
    "  ENDLOOP.",
    "",
    "  PERFORM frm_write_run_calendar_note.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Resolve a standard calendar indicator through a classic function.",
    "*---------------------------------------------------------------------*",
    "FORM frm_write_run_calendar_note.",
    "  CALL FUNCTION 'DATE_COMPUTE_DAY'",
    "    EXPORTING",
    "      date = sy-datum",
    "    IMPORTING",
    "      day  = gv_weekday",
    "    EXCEPTIONS",
    "      date_invalid = 1",
    "      OTHERS       = 2.",
    "",
    "  IF sy-subrc = 0.",
    "    WRITE: / 'Report weekday indicator:', gv_weekday.",
    "  ELSE.",
    "    WRITE: / 'Report weekday indicator is unavailable'.",
    "  ENDIF.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Append one audit message with a monotonically increasing sequence.",
    "*---------------------------------------------------------------------*",
    "FORM frm_add_audit",
    "  USING",
    "    iv_category TYPE char12",
    "    iv_message  TYPE string.",
    "",
    "  DATA ls_audit TYPE ty_audit.",
    "",
    "  gv_audit_sequence = gv_audit_sequence + 1.",
    "  ls_audit-sequence = gv_audit_sequence.",
    "  ls_audit-category = iv_category.",
    "  ls_audit-message = iv_message.",
    "  APPEND ls_audit TO gt_audit.",
    "ENDFORM.",
    "",
    "*---------------------------------------------------------------------*",
    "* Print the execution audit after the main report.",
    "*---------------------------------------------------------------------*",
    "FORM frm_write_audit_log.",
    "  DATA ls_audit TYPE ty_audit.",
    "",
    "  IF gt_audit IS INITIAL.",
    "    RETURN.",
    "  ENDIF.",
    "",
    "  SKIP 2.",
    "  WRITE: / 'Execution audit'.",
    "  WRITE: / sy-uline.",
    "",
    "  LOOP AT gt_audit INTO ls_audit.",
    "    WRITE: / ls_audit-sequence,",
    "             8 ls_audit-category,",
    "             24 ls_audit-message.",
    "  ENDLOOP.",
    "ENDFORM."
  ].join("\n");

  function createTemplateBaseStyle(background) {
    return {
      background: background || "default",
      border: "outside-thin",
      font: "MS PGothic",
      "font color": "#111111",
      "font size": 10,
      "font family": "default",
      bold: false,
      italic: false,
      underline: false,
      merge: false,
      align: "left",
      valign: "top",
      wrap: false
    };
  }

  const TEMPLATE_PREVIEW_DEFAULT_OPTIONS = {
    hideEmptyRows: true,
    hideRowsWithoutValues: true,
    expandMultilineRows: true,
    squareCells: true,
    squareCellSize: 18
  };

  function createKeywordDescriptionTemplate() {
    return {
      _options: {
        hideEmptyRows: true,
        hideRowsWithoutValues: false,
        expandMultilineRows: true
      },
      "A1:T1": createTemplateBaseStyle("#dbeef4"),
      A1: {
        text: "{rows.keyword}"
      },
      "U1:AN1": createTemplateBaseStyle("#ffffff"),
      U1: {
        text: "{rows.finalDesc}"
      }
    };
  }

  function createAppendLinesOfTemplate() {
    const template = {
      _options: {
        hideEmptyRows: true,
        hideRowsWithoutValues: true,
        expandMultilineRows: false
      }
    };
    const rows = [
      ["APPEND LINES OF", "{extras.append.source.finalDesc}"],
      ["FROM", "{extras.append.range.from.finalDesc}"],
      ["TO", "{extras.append.range.to.finalDesc}"],
      ["STEP", "{extras.append.range.step.finalDesc}"],
      ["USING KEY", "{extras.append.range.usingKey.value}"],
      ["TO", "{extras.append.target.finalDesc}"]
    ];
    rows.forEach(([label, token], index) => {
      const row = index + 1;
      template[`A${row}:T${row}`] = createTemplateBaseStyle("#dbeef4");
      template[`A${row}`] = { text: label };
      template[`U${row}:AN${row}`] = createTemplateBaseStyle("#ffffff");
      template[`U${row}`] = { text: token };
    });
    return template;
  }

  const UNIFIED_KEYWORD_ROW_TEMPLATE_V1 = createKeywordDescriptionTemplate();

  const ASSIGNMENT_ROW_TEMPLATE_V1 = {
    _options: {
      hideEmptyRows: true,
      hideRowsWithoutValues: true,
      expandMultilineRows: false
    },
    "A1:T1": createTemplateBaseStyle("#dbeef4"),
    A1: {
      text: "Đích"
    },
    "U1:AN1": createTemplateBaseStyle("#dbeef4"),
    U1: {
      text: "Nguồn"
    },
    "A2:T2": createTemplateBaseStyle("#ffffff"),
    A2: {
      text: "{values.target.finalDesc}"
    },
    "U2:AN2": createTemplateBaseStyle("#ffffff"),
    U2: {
      text: "{values.expr.finalDesc}"
    }
  };

  function createConditionRowTemplate() {
    return {
      _options: {
        hideEmptyRows: true,
        hideRowsWithoutValues: true,
        expandMultilineRows: true
      },
      "A1:T1": createTemplateBaseStyle("#dbeef4"),
      A1: {
        text: "Điều kiện trái"
      },
      "U1:AN1": createTemplateBaseStyle("#dbeef4"),
      U1: {
        text: "Toán tử"
      },
      "AO1:BH1": createTemplateBaseStyle("#dbeef4"),
      AO1: {
        text: "Điều kiện phải"
      },
      "BI1:CB1": createTemplateBaseStyle("#dbeef4"),
      BI1: {
        text: "Kết nối"
      },
      "A2:T2": createTemplateBaseStyle("#ffffff"),
      A2: {
        text: "{extras.ifCondition.conditions.leftOperandDecl.finalDesc}"
      },
      "U2:AN2": createTemplateBaseStyle("#ffffff"),
      U2: {
        text: "{extras.ifCondition.conditions.comparisonOperator}"
      },
      "AO2:BH2": createTemplateBaseStyle("#ffffff"),
      AO2: {
        text: "{extras.ifCondition.conditions.rightOperandDecl.finalDesc}"
      },
      "BI2:CB2": createTemplateBaseStyle("#ffffff"),
      BI2: {
        text: "{extras.ifCondition.conditions.logicalConnector}"
      }
    };
  }

  const TEMPLATE_DEFAULT_CONFIG_V1 = {
    version: 1,
    templates: {
      DEFAULT: UNIFIED_KEYWORD_ROW_TEMPLATE_V1,
      APPEND: createKeywordDescriptionTemplate(),
      APPEND_LINES_OF: createAppendLinesOfTemplate(),
      ASSIGNMENT: ASSIGNMENT_ROW_TEMPLATE_V1,
      CALL_FUNCTION: createKeywordDescriptionTemplate(),
      CASE: createKeywordDescriptionTemplate(),
      CLEAR: createKeywordDescriptionTemplate(),
      CONSTANTS: createKeywordDescriptionTemplate(),
      DATA: createKeywordDescriptionTemplate(),
      DELETE_ITAB: createKeywordDescriptionTemplate(),
      DO: createKeywordDescriptionTemplate(),
      ELSE: createKeywordDescriptionTemplate(),
      ELSEIF: createConditionRowTemplate(),
      "FIELD-SYMBOLS": createKeywordDescriptionTemplate(),
      IF: createConditionRowTemplate(),
      LOOP_AT_ITAB: createKeywordDescriptionTemplate(),
      MESSAGE: createKeywordDescriptionTemplate(),
      MODIFY_ITAB: createKeywordDescriptionTemplate(),
      "MOVE-CORRESPONDING": createKeywordDescriptionTemplate(),
      PARAMETERS: createKeywordDescriptionTemplate(),
      PERFORM: createKeywordDescriptionTemplate(),
      READ_TABLE: createKeywordDescriptionTemplate(),
      SELECT: createKeywordDescriptionTemplate(),
      "SELECT-OPTIONS": createKeywordDescriptionTemplate(),
      SORT_ITAB: createKeywordDescriptionTemplate(),
      TYPES: createKeywordDescriptionTemplate(),
      WHEN: createKeywordDescriptionTemplate(),
      WRITE: createKeywordDescriptionTemplate()
    }
  };

  for (const templateDef of Object.values(TEMPLATE_DEFAULT_CONFIG_V1.templates)) {
    if (!templateDef || typeof templateDef !== "object" || Array.isArray(templateDef)) {
      continue;
    }
    const currentOptions = templateDef._options && typeof templateDef._options === "object" && !Array.isArray(templateDef._options)
      ? templateDef._options
      : {};
    templateDef._options = { ...TEMPLATE_PREVIEW_DEFAULT_OPTIONS, ...currentOptions };
  }

  function setError(message) {
    els.error.textContent = message ? String(message) : "";
  }

  function parseDateCandidate(value) {
    const raw = String(value || "").trim();
    if (!raw) {
      return null;
    }
    const date = new Date(raw);
    return Number.isNaN(date.getTime()) ? null : date;
  }

  function formatDateTime(value) {
    const date = value instanceof Date ? value : parseDateCandidate(value);
    if (!date) {
      return "";
    }
    try {
      return new Intl.DateTimeFormat(undefined, {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit"
      }).format(date);
    } catch {
      return date.toLocaleString();
    }
  }

  function getMetaContent(name) {
    try {
      const el = document.querySelector(`meta[name="${name}"]`);
      if (!el) {
        return "";
      }
      return String(el.getAttribute("content") || "").trim();
    } catch {
      return "";
    }
  }

  function renderBuildInfo() {
    if (!els.buildInfo) {
      return;
    }

    const manualVersion = getMetaContent("abap-viewer-version");
    const manualUpdatedAt = getMetaContent("abap-viewer-updated-at");
    const manualNote = getMetaContent("abap-viewer-updated-note");
    const parsedManualDate = parseDateCandidate(manualUpdatedAt);
    const fallbackDate = parseDateCandidate(document.lastModified);
    const versionPrefix = manualVersion ? `${manualVersion} | ` : "";

    if (manualUpdatedAt || manualVersion) {
      const display = parsedManualDate ? formatDateTime(parsedManualDate) : manualUpdatedAt;
      const updatedText = display || "manual timestamp not set";
      els.buildInfo.textContent = `Updated: ${versionPrefix}${updatedText} (manual)`;
      els.buildInfo.title = manualNote || "Manual timestamp from <meta name=\"abap-viewer-updated-at\">.";
      return;
    }

    if (fallbackDate) {
      els.buildInfo.textContent = `Updated: ${formatDateTime(fallbackDate)} (from document.lastModified)`;
      els.buildInfo.title = "No manual timestamp found. Showing document.lastModified.";
      return;
    }

    els.buildInfo.textContent = "Updated: unknown";
    els.buildInfo.title = "No manual timestamp and no document.lastModified available.";
  }

  function normalizeId(id) {
    if (id === null || id === undefined) {
      return "";
    }
    return String(id);
  }

  function flattenEntryMap(map) {
    if (!map || typeof map !== "object") {
      return [];
    }

    const out = [];
    for (const key of Object.keys(map)) {
      const entryOrList = map[key];
      if (Array.isArray(entryOrList)) {
        for (const entry of entryOrList) {
          if (entry && typeof entry === "object") {
            out.push(entry);
          }
        }
        continue;
      }
      if (entryOrList && typeof entryOrList === "object") {
        out.push(entryOrList);
      }
    }
    return out;
  }

  function getKeywordEntries(obj) {
    if (!obj) {
      return [];
    }
    if (Array.isArray(obj.keywords)) {
      return obj.keywords;
    }
    return flattenEntryMap(obj.keywords);
  }

  function getValueEntries(obj) {
    if (!obj) {
      return [];
    }
    if (Array.isArray(obj.values)) {
      return obj.values;
    }
    return flattenEntryMap(obj.values);
  }

  function getFirstValueFromValues(values, key) {
    if (!values) {
      return "";
    }

    if (Array.isArray(values)) {
      const match = values.find((v) => v && v.name === key && v.value);
      return match ? String(match.value) : "";
    }

    if (typeof values !== "object") {
      return "";
    }

    const entryOrList = values[key];
    const entry = Array.isArray(entryOrList) ? entryOrList[0] : entryOrList;
    return entry && entry.value ? String(entry.value) : "";
  }

  function loadStorageObject(key) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) {
        return {};
      }
      const parsed = JSON.parse(raw);
      return parsed && typeof parsed === "object" ? parsed : {};
    } catch {
      return {};
    }
  }

  function loadDescOverrides() {
    return loadStorageObject(DESC_STORAGE_KEY_V2);
  }

  function loadLegacyDescOverrides() {
    return loadStorageObject(DESC_STORAGE_KEY_LEGACY_V1);
  }

  function saveDescOverrides() {
    try {
      localStorage.setItem(DESC_STORAGE_KEY_V2, JSON.stringify(state.descOverrides || {}));
    } catch {
      // ignore
    }
  }

  function loadStorageArray(key) {
    try {
      const raw = localStorage.getItem(key);
      if (!raw) {
        return [];
      }
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }

  function normalizeSettings(value) {
    const input = value && typeof value === "object" && !Array.isArray(value) ? value : {};

    const normalizeDeclDesc = typeof input.normalizeDeclDesc === "boolean"
      ? input.normalizeDeclDesc
      : DEFAULT_SETTINGS.normalizeDeclDesc;

    const declFilterTypes = Array.isArray(input.declFilterTypes)
      ? input.declFilterTypes
          .map((t) => String(t || "").trim().toUpperCase())
          .filter((t) => t && DECL_TYPE_OPTIONS.includes(t))
      : [];

    const structDescTemplate = typeof input.structDescTemplate === "string" && input.structDescTemplate.trim()
      ? input.structDescTemplate
      : DEFAULT_SETTINGS.structDescTemplate;

    const nameTemplatesByCode = {};
    const inputNameTemplates = input.nameTemplatesByCode && typeof input.nameTemplatesByCode === "object"
      ? input.nameTemplatesByCode
      : {};

    for (const opt of NAME_CODE_OPTIONS) {
      const code = opt.code;
      const rawTemplate = Object.prototype.hasOwnProperty.call(inputNameTemplates, code)
        ? inputNameTemplates[code]
        : DEFAULT_SETTINGS.nameTemplatesByCode[code];

      const template = typeof rawTemplate === "string" && rawTemplate.trim()
        ? rawTemplate
        : DEFAULT_SETTINGS.nameTemplatesByCode[code];

      nameTemplatesByCode[code] = template;
    }

    return {
      normalizeDeclDesc,
      declFilterTypes: declFilterTypes.length ? declFilterTypes : DEFAULT_SETTINGS.declFilterTypes.slice(),
      structDescTemplate,
      nameTemplatesByCode
    };
  }

  function loadSettings() {
    return normalizeSettings(loadStorageObject(SETTINGS_STORAGE_KEY_V1));
  }

  function saveSettings(settings) {
    try {
      localStorage.setItem(SETTINGS_STORAGE_KEY_V1, JSON.stringify(settings || {}));
    } catch {
      // ignore
    }
  }

  function setTemplateConfigError(message) {
    if (!els.templateConfigError) {
      return;
    }
    els.templateConfigError.textContent = message ? String(message) : "";
  }

  function setTemplatePreviewMessage(message) {
    if (!els.templatePreviewOutput) {
      return;
    }
    els.templatePreviewOutput.classList.add("muted");
    els.templatePreviewOutput.replaceChildren();
    els.templatePreviewOutput.textContent = message || "";
  }

  function cloneJsonValue(value) {
    try {
      return JSON.parse(JSON.stringify(value));
    } catch {
      return null;
    }
  }

  function getDefaultTemplateConfig() {
    const cloned = cloneJsonValue(TEMPLATE_DEFAULT_CONFIG_V1);
    return cloned && typeof cloned === "object" ? cloned : { version: 1, templates: {} };
  }

  function templateDefinitionsEqual(left, right) {
    try {
      return JSON.stringify(left) === JSON.stringify(right);
    } catch {
      return false;
    }
  }

  function mergeMissingDefaultTemplatesInPlace(config) {
    if (!config || typeof config !== "object" || Array.isArray(config)) {
      return false;
    }
    if (!config.templates || typeof config.templates !== "object" || Array.isArray(config.templates)) {
      return false;
    }

    let changed = false;
    if (!Object.prototype.hasOwnProperty.call(config.templates, "APPEND_LINES_OF")) {
      const legacyAppend = config.templates.APPEND;
      const defaultAppend = TEMPLATE_DEFAULT_CONFIG_V1.templates.APPEND;
      const dedicatedDefault = TEMPLATE_DEFAULT_CONFIG_V1.templates.APPEND_LINES_OF;
      const sourceTemplate = legacyAppend && !templateDefinitionsEqual(legacyAppend, defaultAppend)
        ? legacyAppend
        : dedicatedDefault;
      const cloned = cloneJsonValue(sourceTemplate);
      if (cloned && typeof cloned === "object") {
        config.templates.APPEND_LINES_OF = cloned;
        changed = true;
      }
    }
    for (const [templateKey, templateDef] of Object.entries(TEMPLATE_DEFAULT_CONFIG_V1.templates)) {
      if (Object.prototype.hasOwnProperty.call(config.templates, templateKey)) {
        continue;
      }
      const cloned = cloneJsonValue(templateDef);
      if (!cloned || typeof cloned !== "object") {
        continue;
      }
      config.templates[templateKey] = cloned;
      changed = true;
    }
    return changed;
  }

  function normalizeTemplateAliasToken(value) {
    return String(value || "")
      .trim()
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/\s+/g, " ");
  }


  function parseCellRef(cellRef) {
    const raw = String(cellRef || "").trim().toUpperCase();
    const match = /^([A-Z]+)([1-9][0-9]*)$/.exec(raw);
    if (!match) {
      throw new Error(`Invalid cell ref "${cellRef}". Expected format like A1.`);
    }

    const letters = match[1];
    const row = Number(match[2]) || 0;
    let col = 0;
    for (let i = 0; i < letters.length; i += 1) {
      col = (col * 26) + (letters.charCodeAt(i) - 64);
    }

    if (!row || !col) {
      throw new Error(`Invalid cell ref "${cellRef}".`);
    }

    return { row, col, raw };
  }

  function parseRangeKey(rangeKey) {
    const raw = String(rangeKey || "").trim().toUpperCase();
    if (!raw) {
      throw new Error("Range key is empty.");
    }

    const parts = raw.split(":").map((item) => item.trim()).filter(Boolean);
    if (!parts.length || parts.length > 2) {
      throw new Error(`Invalid range "${rangeKey}". Expected A1 or A1:B2.`);
    }

    const start = parseCellRef(parts[0]);
    const end = parseCellRef(parts.length > 1 ? parts[1] : parts[0]);

    return {
      key: raw,
      r1: Math.min(start.row, end.row),
      c1: Math.min(start.col, end.col),
      r2: Math.max(start.row, end.row),
      c2: Math.max(start.col, end.col)
    };
  }

  function isTemplateOptionConfigKey(rawKey) {
    const key = String(rawKey || "").trim().toLowerCase();
    if (!key) {
      return false;
    }
    return (
      key === "_options"
      || key === "options"
      || key === "ranges"
      || key === "compact"
      || key === "hideemptyrows"
      || key === "hiderowswithoutvalues"
      || key === "expandmultilinerows"
      || key === "removeemptyrows"
      || key === "removeemptyrowsadvanced"
      || key === "removeemptyrowsadv"
      || key === "expandarrayrows"
      || key === "arraytorows"
    );
  }

  function validateTemplateConfig(config) {
    const errors = [];
    if (!config || typeof config !== "object" || Array.isArray(config)) {
      return { valid: false, errors: ["Config must be a JSON object."] };
    }

    const version = Number(config.version);
    if (version !== 1) {
      errors.push("Config.version must be 1.");
    }

    const templates = config.templates;
    if (!templates || typeof templates !== "object" || Array.isArray(templates)) {
      errors.push("Config.templates must be an object.");
      return { valid: false, errors };
    }

    const templateKeys = Object.keys(templates);
    if (!templateKeys.length) {
      errors.push("Config.templates must contain at least one template key.");
      return { valid: false, errors };
    }

    for (const templateKey of templateKeys) {
      const templateDef = templates[templateKey];
      if (!templateDef || typeof templateDef !== "object" || Array.isArray(templateDef)) {
        errors.push(`templates.${templateKey} must be an object of range -> style.`);
        continue;
      }

      const hasRangesObject = Object.prototype.hasOwnProperty.call(templateDef, "ranges");
      const ranges = hasRangesObject ? templateDef.ranges : templateDef;
      if (!ranges || typeof ranges !== "object" || Array.isArray(ranges)) {
        errors.push(`templates.${templateKey}.ranges must be an object of range -> style.`);
        continue;
      }

      const optionCandidates = ["_options", "options"];
      for (const optKey of optionCandidates) {
        if (!Object.prototype.hasOwnProperty.call(templateDef, optKey)) {
          continue;
        }
        const optValue = templateDef[optKey];
        if (!optValue || typeof optValue !== "object" || Array.isArray(optValue)) {
          errors.push(`templates.${templateKey}.${optKey} must be an object.`);
        }
      }

      for (const rangeKey of Object.keys(ranges)) {
        if (isTemplateOptionConfigKey(rangeKey)) {
          continue;
        }
        try {
          parseRangeKey(rangeKey);
        } catch (err) {
          errors.push(`templates.${templateKey}.${rangeKey}: ${err && err.message ? err.message : err}`);
        }

        const cellConfig = ranges[rangeKey];
        if (!cellConfig || typeof cellConfig !== "object" || Array.isArray(cellConfig)) {
          errors.push(`templates.${templateKey}.${rangeKey} must be an object.`);
        }
      }
    }

    return { valid: errors.length === 0, errors };
  }

  function loadTemplateConfig() {
    try {
      const raw = localStorage.getItem(TEMPLATE_CONFIG_STORAGE_KEY_V1);
      if (!raw) {
        return getDefaultTemplateConfig();
      }
      const parsed = JSON.parse(raw);
      const check = validateTemplateConfig(parsed);
      if (!check.valid) {
        return getDefaultTemplateConfig();
      }
      return parsed;
    } catch {
      return getDefaultTemplateConfig();
    }
  }

  function saveTemplateConfig(config) {
    try {
      localStorage.setItem(TEMPLATE_CONFIG_STORAGE_KEY_V1, JSON.stringify(config || {}));
    } catch {
      // ignore
    }
  }

  function normalizeTheme(value) {
    return value === "light" ? "light" : "dark";
  }

  function loadTheme() {
    try {
      return normalizeTheme(localStorage.getItem(THEME_STORAGE_KEY_V1) || "");
    } catch {
      return "dark";
    }
  }

  function applyTheme(nextTheme, { save } = {}) {
    const normalized = normalizeTheme(nextTheme);
    state.theme = normalized;
    document.documentElement.setAttribute("data-theme", normalized);

    if (els.themeToggle) {
      els.themeToggle.checked = normalized === "dark";
    }

    if (save === false) {
      return;
    }

    try {
      localStorage.setItem(THEME_STORAGE_KEY_V1, normalized);
    } catch {
      // ignore
    }
  }

  function clampNumber(value, min, max) {
    return Math.min(max, Math.max(min, value));
  }

  function normalizeLayoutSplit(value) {
    const numeric = Number(value);
    if (!Number.isFinite(numeric)) {
      return LAYOUT_SPLIT_DEFAULT;
    }
    return clampNumber(numeric, LAYOUT_SPLIT_MIN, LAYOUT_SPLIT_MAX);
  }

  function loadLayoutSplit() {
    try {
      return normalizeLayoutSplit(localStorage.getItem(LAYOUT_SPLIT_STORAGE_KEY_V1));
    } catch {
      return LAYOUT_SPLIT_DEFAULT;
    }
  }

  function saveLayoutSplit(value) {
    try {
      localStorage.setItem(LAYOUT_SPLIT_STORAGE_KEY_V1, String(normalizeLayoutSplit(value)));
    } catch {
      // ignore
    }
  }

  function updateSplitterAria(leftPercent) {
    if (!els.panelSplitter) {
      return;
    }

    const left = Math.round(leftPercent);
    const right = Math.round(100 - leftPercent);
    els.panelSplitter.setAttribute("aria-valuemin", String(LAYOUT_SPLIT_MIN));
    els.panelSplitter.setAttribute("aria-valuemax", String(LAYOUT_SPLIT_MAX));
    els.panelSplitter.setAttribute("aria-valuenow", String(left));
    els.panelSplitter.setAttribute("aria-valuetext", `${left}% code, ${right}% output`);
  }

  function applyLayoutSplit(nextPercent, { save } = {}) {
    const normalized = normalizeLayoutSplit(nextPercent);
    const previous = Number(state.layoutLeftPane);
    state.layoutLeftPane = normalized;
    document.documentElement.style.setProperty("--layout-left-pane", `${normalized}%`);
    updateSplitterAria(normalized);

    if (
      Number.isFinite(previous)
      && Math.abs(previous - normalized) >= 0.01
      && typeof window !== "undefined"
      && typeof window.dispatchEvent === "function"
    ) {
      window.dispatchEvent(new Event("abap-viewer-layout-resize"));
    }

    if (save === false) {
      return;
    }

    saveLayoutSplit(normalized);
  }

  function isCompactLayout() {
    if (typeof window.matchMedia === "function") {
      return window.matchMedia(MOBILE_LAYOUT_QUERY).matches;
    }
    return window.innerWidth <= 980;
  }

  function setLayoutResizing(active) {
    if (!els.mainLayout) {
      return;
    }
    els.mainLayout.classList.toggle("is-resizing", Boolean(active));
  }

  function initLayoutSplitter() {
    applyLayoutSplit(loadLayoutSplit(), { save: false });

    if (!els.mainLayout || !els.panelSplitter) {
      return;
    }

    let dragging = false;
    let activePointerId = null;

    function applySplitFromClientX(clientX) {
      const layoutRect = els.mainLayout.getBoundingClientRect();
      const splitterRect = els.panelSplitter.getBoundingClientRect();
      const usableWidth = layoutRect.width - splitterRect.width;
      if (usableWidth <= 0) {
        return;
      }

      const leftWidth = clientX - layoutRect.left - (splitterRect.width / 2);
      const leftPercent = (leftWidth / usableWidth) * 100;
      applyLayoutSplit(leftPercent, { save: false });
    }

    function onPointerMove(ev) {
      if (!dragging || isCompactLayout()) {
        return;
      }
      applySplitFromClientX(ev.clientX);
      ev.preventDefault();
    }

    function stopDragging() {
      if (!dragging) {
        return;
      }
      dragging = false;
      setLayoutResizing(false);
      if (activePointerId !== null && typeof els.panelSplitter.releasePointerCapture === "function") {
        try {
          els.panelSplitter.releasePointerCapture(activePointerId);
        } catch {
          // ignore
        }
      }
      activePointerId = null;
      saveLayoutSplit(state.layoutLeftPane);
      window.removeEventListener("pointermove", onPointerMove);
      window.removeEventListener("pointerup", stopDragging);
      window.removeEventListener("pointercancel", stopDragging);
    }

    els.panelSplitter.addEventListener("pointerdown", (ev) => {
      if (ev.button !== 0 || isCompactLayout()) {
        return;
      }

      dragging = true;
      activePointerId = ev.pointerId;
      setLayoutResizing(true);

      if (typeof els.panelSplitter.setPointerCapture === "function") {
        try {
          els.panelSplitter.setPointerCapture(ev.pointerId);
        } catch {
          // ignore
        }
      }

      applySplitFromClientX(ev.clientX);
      window.addEventListener("pointermove", onPointerMove);
      window.addEventListener("pointerup", stopDragging);
      window.addEventListener("pointercancel", stopDragging);
      ev.preventDefault();
    });

    els.panelSplitter.addEventListener("keydown", (ev) => {
      if (isCompactLayout()) {
        return;
      }
      if (ev.key !== "ArrowLeft" && ev.key !== "ArrowRight") {
        return;
      }

      const step = ev.shiftKey ? 5 : 2;
      const delta = ev.key === "ArrowRight" ? step : -step;
      applyLayoutSplit(state.layoutLeftPane + delta);
      ev.preventDefault();
    });

    window.addEventListener("resize", () => {
      if (isCompactLayout()) {
        setLayoutResizing(false);
        return;
      }
      applyLayoutSplit(state.layoutLeftPane, { save: false });
    });
  }

  function renderSettingsModalUi() {
    if (!els.settingsModal) {
      return;
    }

    const settings = state.settings || loadSettings();
    state.settings = settings;

    if (els.settingsNormalizeDesc) {
      els.settingsNormalizeDesc.checked = Boolean(settings.normalizeDeclDesc);
    }

    if (els.settingsDeclTypes) {
      els.settingsDeclTypes.replaceChildren();
      for (const type of DECL_TYPE_OPTIONS) {
        const label = document.createElement("label");
        label.className = "toggle";

        const input = document.createElement("input");
        input.type = "checkbox";
        input.value = type;
        input.checked = Array.isArray(settings.declFilterTypes) && settings.declFilterTypes.includes(type);

        label.appendChild(input);
        label.appendChild(document.createTextNode(type));
        els.settingsDeclTypes.appendChild(label);
      }
    }

    if (els.settingsStructTemplate) {
      els.settingsStructTemplate.value = settings.structDescTemplate || DEFAULT_SETTINGS.structDescTemplate;
    }

    if (els.settingsNameTemplates) {
      els.settingsNameTemplates.replaceChildren();

      const table = document.createElement("table");
      const thead = document.createElement("thead");
      const headRow = document.createElement("tr");
      for (const title of ["code", "label", "template"]) {
        const th = document.createElement("th");
        th.textContent = title;
        headRow.appendChild(th);
      }
      thead.appendChild(headRow);
      table.appendChild(thead);

      const tbody = document.createElement("tbody");
      for (const opt of NAME_CODE_OPTIONS) {
        const tr = document.createElement("tr");

        const codeCell = document.createElement("td");
        codeCell.textContent = opt.code;
        tr.appendChild(codeCell);

        const labelCell = document.createElement("td");
        labelCell.textContent = opt.label;
        tr.appendChild(labelCell);

        const tplCell = document.createElement("td");
        const input = document.createElement("input");
        input.type = "text";
        input.style.width = "100%";
        input.setAttribute("data-code", opt.code);
        input.value = (settings.nameTemplatesByCode && settings.nameTemplatesByCode[opt.code])
          ? String(settings.nameTemplatesByCode[opt.code] || "")
          : String(DEFAULT_SETTINGS.nameTemplatesByCode[opt.code] || "");

        tplCell.appendChild(input);
        tr.appendChild(tplCell);

        tbody.appendChild(tr);
      }
      table.appendChild(tbody);

      els.settingsNameTemplates.appendChild(table);
    }
  }

  function openSettingsModal() {
    if (!els.settingsModal) {
      return;
    }

    if (!els.jsonModal.hidden) {
      closeJsonModal();
    }
    if (!els.editModal.hidden) {
      closeEditModal();
    }

    renderSettingsModalUi();
    els.settingsModal.hidden = false;
  }

  function closeSettingsModal() {
    if (!els.settingsModal) {
      return;
    }
    els.settingsModal.hidden = true;
  }

window.AbapViewerModules.factories = window.AbapViewerModules.factories || {};
window.AbapViewerModules.factories["01-core"] = function registerCore(runtime) {
  const targetRuntime = runtime || (window.AbapViewerRuntime = window.AbapViewerRuntime || {});
  targetRuntime.api = targetRuntime.api || {};
  targetRuntime.els = els;
  targetRuntime.state = state;
  targetRuntime.constants = {
    DESC_STORAGE_KEY_V2,
    DESC_STORAGE_KEY_LEGACY_V1,
    SETTINGS_STORAGE_KEY_V1,
    TEMPLATE_CONFIG_STORAGE_KEY_V1,
    THEME_STORAGE_KEY_V1,
    LAYOUT_SPLIT_STORAGE_KEY_V1,
    LAYOUT_SPLIT_DEFAULT,
    LAYOUT_SPLIT_MIN,
    LAYOUT_SPLIT_MAX,
    MOBILE_LAYOUT_QUERY,
    RENDER_TREE_OPTIONS,
    DECL_TYPE_OPTIONS,
    NAME_CODE_OPTIONS,
    DEFAULT_SETTINGS,
    TEMPLATE_DEFAULT_CONFIG_V1,
    SAMPLE_ABAP
  };
  window.AbapViewerModules.parts["01-core"] = true;
};
window.AbapViewerModules.factories["01-core"](window.AbapViewerRuntime);
