/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: case.json");
    return;
  }

  const config = {
    "_sourceFile": "case.json",
    "object": "CASE",
    "match": {
      "startKeyword": "CASE"
    },
    "block": {
      "endKeyword": "ENDCASE"
    },
    "keywordLabels": {
      "CASE": "stmt"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "CASE",
        "name": "expr",
        "label": "expression",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
