/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: delete-itab.json");
    return;
  }

  const config = {
    "_sourceFile": "delete-itab.json",
    "object": "DELETE_ITAB",
    "match": {
      "startKeyword": "DELETE"
    },
    "extras": {
      "type": "deleteItab"
    },
    "keywordLabels": {
      "DELETE": "stmt",
      "FROM": "from",
      "INDEX": "index",
      "WHERE": "where",
      "ADJACENT": "adjacent",
      "DUPLICATES": "duplicates",
      "COMPARING": "comparing"
    },
    "keywordPhrases": {
      "ADJACENT DUPLICATES": "adjacent-duplicates",
      "DELETE ADJACENT DUPLICATES": "delete-adjacent-duplicates"
    },
    "captureRules": [
      {
        "after": "DELETE",
        "name": "target",
        "label": "target"
      },
      {
        "after": "FROM",
        "name": "from",
        "label": "from"
      },
      {
        "after": "INDEX",
        "name": "index",
        "label": "index"
      },
      {
        "after": "WHERE",
        "name": "where",
        "label": "where",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
