/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: do.json");
    return;
  }

  const config = {
    "_sourceFile": "do.json",
    "object": "DO",
    "match": {
      "startKeyword": "DO"
    },
    "block": {
      "endKeyword": "ENDDO"
    },
    "keywordLabels": {
      "DO": "stmt",
      "TIMES": "times"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "DO",
        "name": "times",
        "label": "times"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
