/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: perform.json");
    return;
  }

  const config = {
    "_sourceFile": "perform.json",
    "object": "PERFORM",
    "match": {
      "startKeyword": "PERFORM"
    },
    "extras": {
      "type": "performCall"
    },
    "keywordLabels": {
      "PERFORM": "stmt",
      "IN": "in",
      "PROGRAM": "program",
      "USING": "using",
      "CHANGING": "changing",
      "TABLES": "tables",
      "IF": "if"
    },
    "keywordPhrases": {
      "IN PROGRAM": "in-program"
    },
    "captureRules": [
      {
        "after": "PERFORM",
        "name": "form",
        "label": "form-name",
        "descKey": "form"
      },
      {
        "after": "IN PROGRAM",
        "name": "program",
        "label": "program"
      },
      {
        "after": "USING",
        "name": "usingRaw",
        "label": "using",
        "capture": "rest",
        "stopTokens": [
          "CHANGING",
          "TABLES",
          "IF"
        ]
      },
      {
        "after": "CHANGING",
        "name": "changingRaw",
        "label": "changing",
        "capture": "rest",
        "stopTokens": [
          "USING",
          "TABLES",
          "IF"
        ]
      },
      {
        "after": "TABLES",
        "name": "tablesRaw",
        "label": "tables",
        "capture": "rest",
        "stopTokens": [
          "USING",
          "CHANGING",
          "IF"
        ]
      },
      {
        "after": "IF",
        "name": "ifCondition",
        "label": "if",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
