/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: try.json");
    return;
  }

  const config = {
    "_sourceFile": "try.json",
    "object": "TRY",
    "match": {
      "startKeyword": "TRY"
    },
    "block": {
      "endKeyword": "ENDTRY"
    },
    "keywordLabels": {
      "TRY": "stmt"
    },
    "keywordPhrases": {},
    "captureRules": []
  };
  window.AbapParser.registerConfig(config);
})();
