"use strict";

const fs = require("fs");
const path = require("path");
const { pathToFileURL } = require("url");
const { JSDOM } = require("jsdom");

const repoRoot = path.resolve(__dirname, "..", "..");
const viewerIndexPath = path.resolve(repoRoot, "viewer", "index.html");
const inlineBannerLines = [
  "<!--",
  "  AUTO-GENERATED FILE",
  "  Source: viewer/index.html",
  "  Generator: scripts/build-inline-viewer.py",
  "  Do not edit this file directly. Regenerate instead.",
  "-->",
  ""
];

function escapeInlineScript(source) {
  return String(source || "").replace(/<\/script>/gi, "<\\/script>");
}

function isRemoteUrl(url) {
  return /^(?:https?:)?\/\//i.test(String(url || "").trim());
}

function resolveViewerAssetPath(baseDir, relPath) {
  const href = String(relPath || "").trim();
  if (!href) {
    throw new Error("Viewer asset path is empty.");
  }
  if (isRemoteUrl(href)) {
    throw new Error(`Viewer must stay offline-only. Remote asset found: ${href}`);
  }
  const absolutePath = path.resolve(baseDir, href);
  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Viewer asset missing: ${href}`);
  }
  return absolutePath;
}

function inlineViewerStyles(html, baseDir) {
  return html.replace(/<link\b[^>]*rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>/gi, (tag, href) => {
    const cssPath = resolveViewerAssetPath(baseDir, href);
    return `<style>\n/* inlined from: ${href} */\n${fs.readFileSync(cssPath, "utf8").trimEnd()}\n</style>`;
  });
}

function inlineViewerScripts(html, baseDir) {
  return html.replace(/<script\b([^>]*)\bsrc=["']([^"']+)["']([^>]*)><\/script>/gi, (block, before, src) => {
    const scriptPath = resolveViewerAssetPath(baseDir, src);
    return `<script>\n// inlined from: ${src}\n${escapeInlineScript(fs.readFileSync(scriptPath, "utf8").trimEnd())}\n</script>`;
  });
}

function collectDisallowedCssUrls(html) {
  const disallowed = [];
  const cssUrlPattern = /\burl\(\s*(["']?)([^"')]+)\1\s*\)/gi;
  let match = cssUrlPattern.exec(html);
  while (match) {
    const url = String(match[2] || "").trim();
    if (!url) {
      match = cssUrlPattern.exec(html);
      continue;
    }
    if (/^(?:data:|#)/i.test(url)) {
      match = cssUrlPattern.exec(html);
      continue;
    }
    disallowed.push(url);
    match = cssUrlPattern.exec(html);
  }
  return disallowed;
}

function assertSelfContainedInlineHtml(html) {
  if (/<script\b[^>]*\bsrc=/i.test(html)) {
    throw new Error("Inline viewer must not retain <script src=...> tags.");
  }
  if (/<link\b[^>]*rel=["']stylesheet["'][^>]*href=/i.test(html)) {
    throw new Error("Inline viewer must not retain stylesheet link tags.");
  }
  const disallowedCssUrls = collectDisallowedCssUrls(html);
  if (disallowedCssUrls.length) {
    throw new Error(`Inline viewer must not retain CSS url() assets: ${disallowedCssUrls.join(", ")}`);
  }
  const remoteRefs = [];
  const assetPattern = /\b(?:src|href)\s*=\s*["']([^"']+)["']/gi;
  let assetMatch = assetPattern.exec(html);
  while (assetMatch) {
    const url = String(assetMatch[1] || "").trim();
    if (isRemoteUrl(url)) {
      remoteRefs.push(url);
    }
    assetMatch = assetPattern.exec(html);
  }
  if (remoteRefs.length) {
    throw new Error(`Inline viewer must stay offline-only. Remote refs: ${remoteRefs.join(", ")}`);
  }
}

function buildViewerHtmlFromSources() {
  const html = fs.readFileSync(viewerIndexPath, "utf8");
  const baseDir = path.dirname(viewerIndexPath);
  return inlineViewerScripts(inlineViewerStyles(html, baseDir), baseDir);
}

function buildInlineViewerHtmlFromSources() {
  const html = buildViewerHtmlFromSources();
  assertSelfContainedInlineHtml(html);
  return `${inlineBannerLines.join("\n")}${html}`.replace(/\r\n?/g, "\n");
}

function createMatchMediaStub() {
  return function matchMedia(query) {
    return {
      matches: false,
      media: String(query || ""),
      onchange: null,
      addListener() {},
      removeListener() {},
      addEventListener() {},
      removeEventListener() {},
      dispatchEvent() { return false; }
    };
  };
}

function setStableElementMetrics(element, metrics) {
  for (const [key, value] of Object.entries(metrics)) {
    Object.defineProperty(element, key, {
      configurable: true,
      get() {
        return value;
      }
    });
  }
}

function installStorageStubs(window) {
  const createBackingStore = () => new Map();

  function StorageStub(backingStore) {
    Object.defineProperty(this, "__store", {
      configurable: false,
      enumerable: false,
      value: backingStore
    });
  }

  StorageStub.prototype.getItem = function getItem(key) {
    const normalizedKey = String(key || "");
    return this.__store.has(normalizedKey) ? this.__store.get(normalizedKey) : null;
  };
  StorageStub.prototype.setItem = function setItem(key, value) {
    this.__store.set(String(key || ""), String(value || ""));
  };
  StorageStub.prototype.removeItem = function removeItem(key) {
    this.__store.delete(String(key || ""));
  };
  StorageStub.prototype.clear = function clear() {
    this.__store.clear();
  };
  StorageStub.prototype.key = function key(index) {
    const keys = Array.from(this.__store.keys());
    return Number.isInteger(index) && index >= 0 && index < keys.length ? keys[index] : null;
  };
  Object.defineProperty(StorageStub.prototype, "length", {
    configurable: true,
    enumerable: false,
    get() {
      return this.__store.size;
    }
  });

  Object.defineProperty(window, "Storage", {
    configurable: true,
    value: StorageStub
  });

  Object.defineProperty(window, "localStorage", {
    configurable: true,
    value: new StorageStub(createBackingStore())
  });
  Object.defineProperty(window, "sessionStorage", {
    configurable: true,
    value: new StorageStub(createBackingStore())
  });
}

async function loadViewerDom() {
  const html = buildViewerHtmlFromSources();
  const dom = new JSDOM(html, {
    url: pathToFileURL(viewerIndexPath).href,
    runScripts: "dangerously",
    pretendToBeVisual: true,
    beforeParse(window) {
      window.matchMedia = createMatchMediaStub();
      window.requestAnimationFrame = (cb) => window.setTimeout(() => cb(Date.now()), 0);
      window.cancelAnimationFrame = (id) => window.clearTimeout(id);
      window.scrollTo = () => {};
      window.alert = () => {};
      window.confirm = () => true;
      window.prompt = () => "";
      window.URL.createObjectURL = () => "blob:local";
      window.URL.revokeObjectURL = () => {};
      installStorageStubs(window);
      window.__clipboardWrites = [];
      window.navigator.clipboard = {
        writeText: async (text) => {
          window.__clipboardWrites.push({ type: "text", text: String(text || "") });
        },
        write: async (items) => {
          window.__clipboardWrites.push({ type: "items", items });
        }
      };
      if (window.HTMLElement && window.HTMLElement.prototype) {
        window.HTMLElement.prototype.scrollIntoView = function scrollIntoView() {};
      }
    }
  });

  await new Promise((resolve) => {
    dom.window.setTimeout(resolve, 0);
  });

  const runtime = dom.window.AbapViewerRuntime || {};
  const els = runtime.els || {};
  if (!runtime.services || !runtime.services.bootstrap) {
    throw new Error("Viewer service registry did not initialize.");
  }
  if (!els.inputText || !els.templatePreviewOutput || !els.declDescPanel) {
    throw new Error("Viewer runtime did not initialize expected DOM references.");
  }

  setStableElementMetrics(els.inputText, { clientHeight: 540, scrollHeight: 1800 });
  setStableElementMetrics(els.templatePreviewOutput, { clientHeight: 800, scrollHeight: 2400 });

  return dom;
}

async function renderFixture(abapSource) {
  const dom = await loadViewerDom();
  const { window } = dom;
  const runtime = window.AbapViewerRuntime || {};
  const els = runtime.els || {};

  els.inputText.value = String(abapSource || "");
  els.inputText.dispatchEvent(new window.Event("input", { bubbles: true }));
  els.parseBtn.click();

  await new Promise((resolve) => window.setTimeout(resolve, 0));

  return dom;
}

module.exports = {
  assertSelfContainedInlineHtml,
  buildInlineViewerHtmlFromSources,
  buildViewerHtmlFromSources,
  collectDisallowedCssUrls,
  loadViewerDom,
  renderFixture
};
