/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: assignment.json");
    return;
  }

  const config = {
    "_sourceFile": "assignment.json",
    "object": "ASSIGNMENT",
    "match": {
      "type": "assignment"
    },
    "keywordLabels": {
      "=": "assign",
      "+=": "add-assign",
      "-=": "sub-assign",
      "*=": "mul-assign",
      "/=": "div-assign",
      "?=": "cast"
    },
    "keywordPhrases": {},
    "captureRules": []
  };
  window.AbapParser.registerConfig(config);
})();
