/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: class.json");
    return;
  }

  const config = {
    "_sourceFile": "class.json",
    "object": "CLASS",
    "match": {
      "startKeyword": "CLASS"
    },
    "block": {
      "endKeyword": "ENDCLASS"
    },
    "keywordLabels": {
      "CLASS": "stmt",
      "DEFINITION": "definition",
      "IMPLEMENTATION": "implementation",
      "PUBLIC": "public",
      "PROTECTED": "protected",
      "PRIVATE": "private",
      "SECTION": "section",
      "CREATE": "create"
    },
    "keywordPhrases": {
      "PUBLIC SECTION": "public-section",
      "PROTECTED SECTION": "protected-section",
      "PRIVATE SECTION": "private-section",
      "CREATE PUBLIC": "create-public"
    },
    "captureRules": [
      {
        "after": "CLASS",
        "name": "name",
        "label": "class-name",
        "descKey": "name"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
