/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: class-methods.json");
    return;
  }

  const config = {
    "_sourceFile": "class-methods.json",
    "object": "CLASS-METHODS",
    "match": {
      "startKeyword": "CLASS-METHODS"
    },
    "extras": {
      "type": "methodSignature"
    },
    "keywordLabels": {
      "CLASS-METHODS": "stmt",
      "IMPORTING": "importing",
      "EXPORTING": "exporting",
      "CHANGING": "changing",
      "RETURNING": "returning",
      "RAISING": "raising"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "CLASS-METHODS",
        "name": "name",
        "label": "method-name",
        "descKey": "name"
      },
      {
        "after": "IMPORTING",
        "name": "importingRaw",
        "label": "importing",
        "capture": "rest",
        "stopTokens": [
          "EXPORTING",
          "CHANGING",
          "RETURNING",
          "RAISING"
        ]
      },
      {
        "after": "EXPORTING",
        "name": "exportingRaw",
        "label": "exporting",
        "capture": "rest",
        "stopTokens": [
          "IMPORTING",
          "CHANGING",
          "RETURNING",
          "RAISING"
        ]
      },
      {
        "after": "CHANGING",
        "name": "changingRaw",
        "label": "changing",
        "capture": "rest",
        "stopTokens": [
          "IMPORTING",
          "EXPORTING",
          "RETURNING",
          "RAISING"
        ]
      },
      {
        "after": "RETURNING",
        "name": "returningRaw",
        "label": "returning",
        "capture": "rest",
        "stopTokens": [
          "IMPORTING",
          "EXPORTING",
          "CHANGING",
          "RAISING"
        ]
      },
      {
        "after": "RAISING",
        "name": "raisingRaw",
        "label": "raising",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
