/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: elseif.json");
    return;
  }

  const config = {
    "_sourceFile": "elseif.json",
    "object": "ELSEIF",
    "match": {
      "startKeyword": "ELSEIF"
    },
    "extras": {
      "type": "ifCondition"
    },
    "keywordLabels": {
      "ELSEIF": "stmt",
      "AND": "and",
      "OR": "or",
      "NOT": "not",
      "IS": "is",
      "INITIAL": "initial"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "ELSEIF",
        "name": "condition",
        "label": "condition",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
