/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: form.json");
    return;
  }

  const config = {
    "_sourceFile": "form.json",
    "object": "FORM",
    "match": {
      "startKeyword": "FORM"
    },
    "block": {
      "endKeyword": "ENDFORM"
    },
    "extras": {
      "type": "form"
    },
    "keywordLabels": {
      "FORM": "stmt",
      "USING": "using",
      "CHANGING": "changing",
      "TABLES": "tables",
      "RAISING": "raising"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "FORM",
        "name": "name",
        "label": "form-name",
        "descKey": "name"
      },
      {
        "after": "USING",
        "name": "usingRaw",
        "label": "using",
        "capture": "rest",
        "stopTokens": [
          "CHANGING",
          "TABLES",
          "RAISING"
        ]
      },
      {
        "after": "CHANGING",
        "name": "changingRaw",
        "label": "changing",
        "capture": "rest",
        "stopTokens": [
          "USING",
          "TABLES",
          "RAISING"
        ]
      },
      {
        "after": "TABLES",
        "name": "tablesRaw",
        "label": "tables",
        "capture": "rest",
        "stopTokens": [
          "USING",
          "CHANGING",
          "RAISING"
        ]
      },
      {
        "after": "RAISING",
        "name": "raisingRaw",
        "label": "raising",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
