/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: move.json");
    return;
  }

  const config = {
    "_sourceFile": "move.json",
    "object": "MOVE",
    "match": {
      "startKeyword": "MOVE"
    },
    "keywordLabels": {
      "MOVE": "stmt",
      "TO": "to"
    },
    "keywordPhrases": {},
    "captureRules": [
      {
        "after": "MOVE",
        "name": "source",
        "label": "source",
        "capture": "rest",
        "stopTokens": [
          "TO"
        ]
      },
      {
        "after": "TO",
        "name": "target",
        "label": "target",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
