/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: select-options.json");
    return;
  }

  const config = {
    "_sourceFile": "select-options.json",
    "object": "SELECT-OPTIONS",
    "match": {
      "startKeyword": "SELECT-OPTIONS"
    },
    "keywordLabels": {
      "SELECT-OPTIONS": "stmt",
      "FOR": "for",
      "DEFAULT": "default",
      "OBLIGATORY": "obligatory",
      "NO-EXTENSION": "no-extension",
      "NO": "no",
      "INTERVALS": "intervals",
      "LOWER": "lower",
      "CASE": "case",
      "MEMORY": "memory",
      "ID": "id",
      "MODIF": "modif",
      "VISIBLE": "visible",
      "LENGTH": "length"
    },
    "keywordPhrases": {
      "LOWER CASE": "lower-case",
      "NO-EXTENSION": "no-extension",
      "NO INTERVALS": "no-intervals",
      "MEMORY ID": "memory-id",
      "MODIF ID": "modif-id"
    },
    "captureRules": [
      {
        "after": "SELECT-OPTIONS",
        "name": "name",
        "label": "selopt-name",
        "descKey": "name"
      },
      {
        "after": "FOR",
        "name": "for",
        "label": "for"
      },
      {
        "after": "DEFAULT",
        "name": "default",
        "label": "default"
      },
      {
        "after": "LENGTH",
        "name": "length",
        "label": "length"
      },
      {
        "after": "MEMORY ID",
        "name": "memoryId",
        "label": "memory-id"
      },
      {
        "after": "MODIF ID",
        "name": "modifId",
        "label": "modif-id"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
