/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: sort-itab.json");
    return;
  }

  const config = {
    "_sourceFile": "sort-itab.json",
    "object": "SORT_ITAB",
    "match": {
      "startKeyword": "SORT"
    },
    "keywordLabels": {
      "SORT": "stmt",
      "BY": "by",
      "ASCENDING": "ascending",
      "DESCENDING": "descending",
      "AS": "as",
      "TEXT": "text",
      "USING": "using",
      "KEY": "key"
    },
    "keywordPhrases": {
      "USING KEY": "using-key",
      "AS TEXT": "as-text"
    },
    "captureRules": [
      {
        "after": "SORT",
        "name": "itab",
        "label": "itab"
      },
      {
        "after": "BY",
        "name": "by",
        "label": "by",
        "capture": "rest",
        "stopTokens": [
          "ASCENDING",
          "DESCENDING",
          "USING"
        ]
      },
      {
        "after": "USING KEY",
        "name": "usingKey",
        "label": "using-key"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
