/* eslint-disable */
/*
  AUTO-GENERATED FILE

  Source: /configs/*.json
  Generator: /scripts/build-viewer-configs.js

  Do not edit this file directly. Regenerate instead.
*/

(function () {
  "use strict";

  if (!window.AbapParser || typeof window.AbapParser.registerConfig !== "function") {
    console.warn("AbapParser not loaded; config not registered: when.json");
    return;
  }

  const config = {
    "_sourceFile": "when.json",
    "object": "WHEN",
    "match": {
      "startKeyword": "WHEN"
    },
    "keywordLabels": {
      "WHEN": "stmt",
      "OTHERS": "others"
    },
    "keywordPhrases": {
      "WHEN OTHERS": "when-others"
    },
    "captureRules": [
      {
        "after": "WHEN",
        "name": "branch",
        "label": "branch",
        "capture": "rest"
      }
    ]
  };
  window.AbapParser.registerConfig(config);
})();
